---
language: node_js
node_js:
  - "4"

addons:
  chrome: stable

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=node-tests

matrix:
  fast_finish: true

before_install:
  - npm config set spin false

install:
  - npm install


script:
  # Usually, it's ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
