---
language: node_js
node_js:
  - "4"

addons:
  chrome: stable

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  # we recommend new addons test the current and previous LTS
  # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install


script:
  # Usually, it's ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
