---
language: node_js
node_js:
  - "6"

addons:
  chrome: stable

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install
  - bower install

script:
  - node_modules/.bin/ember test
